  name: Nuget Build 

  on: [push]

  jobs:
    nuget:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5   
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
                
      - name : restorePlugin.LocalNotification.sln
        run: nuget restore Source/LocalNotifications/LocalNotifications.csproj

      - name: build Plugin.LocalNotification.csproj
        run: msbuild Source/LocalNotifications/LocalNotifications.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: LocalNotifications
          path: Source/LocalNotifications/bin/Debug/ 

      - name: Push generated package to GitHub registry
        run: nuget push **/*.nupkg -Source "GitHub" -SkipDuplicate
